### ISSUE TITLE
Supplementaries flax growth issues with Iguana Tweaks Reborn

### ISSUE THREAD

**Issue by rckymtnrfc** [Insane-96/IguanaTweaksReborn#149]
Follow the following guideline. Not following this will result in ignored and closed issue.

// Usually only latest versions are supported

**Minecraft Version**: 1.16.5

// Please make sure you're using the latest version before sending a report

Mod Version:  Iguana Tweaks Reborn 2.5.4 and InsaneLib 1.0.1

**Forge Version**: 36.1.13

**What Happens**:  With Iguana Tweaks and Supplementaries installed, the flax crop from Supplementaries has some issues.

When using bonemeal on flax (a 2 high crop) the top stays invisible.  Something is also causing the crop to "pop off" and drop a seed during natural growth.

I did some testing, I planted five flax plants.  Two got to 85% and then sometime after (I assume when it hit 100% growth), they popped off to seed.  The other three all popped while at 57%.

Another weird event I noticed.  Occasionally there is a breaking animation/sound along the top of any flax that are at 42%.  The plant doesn't drop to a seed though, just stays at 42%.  I would guess it's when the plant attempts to grow to 57% and becomes 2 blocks tall.  Eventually it does reach 57% and then pops off like the rest.

//Please send logs even if you don't have any crash
//**Use Gist or Pastebin**

**Logs / Crash reports**: https://pastebin.com/w7SCDSak

//If different from default
**Config**: https://pastebin.com/XujJtHin

**List of mods installed / modpack**:
JEI 7.6.4.88
Supplementaries 0.12.1
The One Probe 3.0.7

**Comment by rckymtnrfc** [comment]
I just did some testing.  I've updated Inguana Tweaks to 2.5.6 but I'm still seeing the same results when using bonemeal as well as the growth issues where the flax crops fail to grow to 100% and instead drop to seeds. 

I believe you said flax was already included in the block blacklist.  Since this was still occurring, I changed it to:
"Block Blacklist" = ["supplementaries:flax"]
but unfortunately these issues still exist.

**Comment by Insane96** [comment]
Fixed (hopefully) in 2.5.7 just released

**Comment by rckymtnrfc** [comment]
Partially fixed.  Bonemeal now works with flax as expected, the top block shows correctly when using bonemeal.

Unfortunately, I'm still having the issue when flax grows naturally.  During natural growth, when the plant goes from 42% to 57% growth (which is when it becomes 2 blocks tall), the top block breaks off instantly and the plant stays at 42% growth.  Eventually it will grow to 57% but before making it to 100% the entire plant will break and drops flax seeds.

I tested 24 plants and only 1 made it to 100% growth.  The other 23 broke and dropped to seed between 57% and 100% growth.

**Comment by Insane96** [comment]
Fixed in 2.5.8
