### ISSUE TITLE
crash to desktop with apotheosis AND create enchantment industry installed

### ISSUE THREAD

**Issue by Ikxale** [Insane-96/IguanaTweaksReborn#266]
Not following this guidline will result in ignored and closed issue.  
Please make sure you're using the latest versions before sending a report.

**Versions**:
* Minecraft:  1.20.1
* Forge: 47.2.20
* IguanaTweaks Reborn:  3.1.13
* InsaneLib: 1.12.1-1.20.1

**What Happens**:  
the game crashes to desktop on launch

//Please send logs even if you don't have any crash  
//**Use Gist or Pastebin**  
**Logs / Crash reports**: 
 [crash-2024-02-17_12.02.15-client.txt](https://github.com/Insane96/IguanaTweaksReborn/files/14320092/crash-2024-02-17_12.02.15-client.txt)

//If different from default
**Config**:  
default

**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?**:  
iguanatweaks + insanelib + maxhealthfix. create + create enchantment industry. Placebo + apotheosis + apothic attributes + patchouli. (grouped so each suite of dependencies is seperated by a ".")

I'm not sure which mod is the ultimate culprit as iguana tweaks works with create:enchantment. create enchantment works with apotheosis and apotheosis works with iguanatweaks.  only when all three are involved will it crash this leads me to believe it is most likely related to how either apotheosis or iguana tweaks handles enchantments or enchantment levels as both are side by side in logs far to the end alongside mention of a level 1000 enchantment. but alas i am no programmer. apologies if this is not a bug on this end.

**Comment by Insane96** [comment]
The mod is not yet to 1.20.2
That said seems to be an incompatiblity with apotheosis

**Comment by Insane96** [comment]
Fixed for the next update

**Comment by CraftyZombie** [comment]
Unfortunately this doesn't seem to fix the issue at hand.
Using Apotheosis 7.3.0 and ITR 3.2.0, still getting this crash.
(Aware I have more mods installed, but the crashlog references ITR, and removing either fixes the issue. In fact, I think it might be the same error.)

Here's my latest.log, debug.log, and crash report. https://gist.github.com/CraftyZombie/4b9ecd08c6f2dc307122a2c1651ba1ab

**Comment by Insane96** [comment]
Fixed again for next update

**Comment by Ikxale** [comment]
> The mod is not yet to 1.20.2 That said seems to be an incompatiblity with apotheosis

1.20.1
typo sorry
